### ISSUE TITLE
Unused file in cuda_docker

### ISSUE THREAD

**Issue by YunchaeChoi** [arcs-skku/EMDC_llvm#10]
In EMDC_llvm/devops/openwhisk/cuda_docker,
There are several files that seem unnecessary. (e.g., hello.c, index.html, ...)
Do they have another purposes?

**Comment by sungin-h** [comment]
hello.c is for the creation HELLO WORLD action
OW's docker-based alternative runtime requires an HTTP server. index.html is for testing the server.
