### ISSUE TITLE
C compiler version

### ISSUE THREAD

**Issue by jeongjaeK** [arcs-skku/EMDC_llvm#11]
In benchmark/MMAP/src/Makefile, there is a makefile. 
Is there any reason about compiling program with c++14? If we use lower version, it can be a problem?
```
vector_example: vector_main.cpp cuvector.cpp
	$(NVCC) $^ -o $@ -lcuda -std=c++14

sync_example: sync_main.cu
	$(NVCC) $^ -o $@ -lcuda -std=c++14
```

**Comment by sungin-h** [comment]
The tutorial came from Intel's tutorial code based on the c++14 standard. But, I didn't check with a lower standard.
