### ISSUE TITLE
In EMDC_llvm/benchmarks/full_interference/run.sh

### ISSUE THREAD

**Issue by YunchaeChoi** [arcs-skku/EMDC_llvm#12]
The purpose of 'cudaMalloc.exe' is unclear because it is binary. If the Makefile of cudaMalloc.exe exists, it would more helpful to read the code.

**Comment by sungin-h** [comment]
The benchmark is to measure cudaMalloc latency on multi processes.
If you run the script, you'll get appended nvprof result.
