### ISSUE TITLE
Usage of cudaDeviceSetLimit(cudaLimitStackSize, 0);

### ISSUE THREAD

**Issue by YunchaeChoi** [arcs-skku/EMDC_llvm#13]
In EMDC_llvm/benchmarks/pt/polybench-gpu-1.0/CUDA/2DCONV/2DConvolution.cu,
line 187, why the stack size have to limited?

187| cudaDeviceSetLimit(cudaLimitStackSize, 0);

**Comment by sungin-h** [comment]
CUDA context allocates GPU's pinned memory. It includes CUDA stack and it would be 216MB on A100(108SMs) GPU. To minimize CUDA stack size, I set the limitation via cudaDeviceSetLimit API.
