### ISSUE TITLE
Fixed values in 2Dconvolution

### ISSUE THREAD

**Issue by jeongjaeK** [arcs-skku/EMDC_llvm#15]
In benchmarks/pt/polybench-gpu-1.0/CUDA/2DCONV/2DConvolution.cu, there are fixed values(c11 = +0.2, c21 = +0.5, ...).
Is there any reason about it?
```
c11 = +0.2;  c21 = +0.5;  c31 = -0.8;
c12 = -0.3;  c22 = +0.6;  c32 = -0.9;
c13 = +0.4;  c23 = +0.7;  c33 = +0.10;
```

**Comment by sungin-h** [comment]
Those values are not fixed by this project. The code is based on Polybench/GPU ( https://web.cse.ohio-state.edu/~pouchet.2/software/polybench/GPU/index.html )
