### ISSUE TITLE
Confused about polybench version

### ISSUE THREAD

**Issue by jeongjaeK** [arcs-skku/EMDC_llvm#18]
In benchmarks/pt/polybench-gpu-1.0/README.txt, there is a sentence "The codes are based on PolyBench 2.0 (with the exception of convolution which isn't part of PolyBench 2.0).".
I'm confused with directory name(polybench-gpu-1.0) and sentence(polybench 2.0). 
Which polybench version is this program use?
```
The codes are based on PolyBench 2.0 (with the exception of convolution which isn't part of PolyBench 2.0).
```

**Comment by sungin-h** [comment]
That is not relative to this project.
