### ISSUE TITLE
Question regarding Nsight profiler result

### ISSUE THREAD

**Issue by an-ys** [arcs-skku/EMDC_llvm#20]
According to "benchmarks/cuda/src/cuda.nvprof", `cudaFree` takes up most of the execution time. Is this because the time includes the `cudaMemsetAsync` calls after the initial `cudaMemset` call?
Is there a way to estimate the execution time for the asynchronous calls and `cudaFree` call?

**Comment by jeongjaeK** [comment]
I recommend to use cudaEvent when estimate the execution time with Synchronization API (ex. cudaEventSynchronize() )
