### ISSUE TITLE
The reason of benchmark candidates in Eager Free

### ISSUE THREAD

**Issue by mtm776** [arcs-skku/EMDC_llvm#32]
Are there some reasons about choosing benchmark candidates in eager free?

**Comment by jeongjaeK** [comment]
We did some analysis for finding benchmark candidates that expect to get performance improvement when using Eager Free. There is 11 benchmarks in polybench and rodinia that can execute eager free. (2MM, 3MM, ATAX, BICG, CORR, COVAR, MVT, dwt2d, backprop, srad_v1, huffman)
