### ISSUE TITLE
The reason of using different streams in eager_launch benchmark

### ISSUE THREAD

**Issue by mtm776** [arcs-skku/EMDC_llvm#33]
Why using different streams in eager_launch benchmark in eager_sched/eager_launch/benchmark/polybench1.0?

**Comment by jeongjaeK** [comment]
Because in our scheduling policy, eager launch task can acquire extra memory when normally scheduled task was terminated or Eager Free was executed. Detailed in eager_sched/eager_launch/monitoring_alg.txt.
