### ISSUE TITLE
 What variables are used in eager_sched/sched.cpp to resolve priorities between tasks?

### ISSUE THREAD

**Issue by alwaysfamaz** [arcs-skku/EMDC_llvm#42]
What variables are used in eager_sched/sched.cpp to resolve priorities between tasks?

**Comment by jeongjaeK** [comment]
We set priorities to task (Normal Launch, Eager Launch task) via cudaCreateStreamWithPriority() in each application's source code. The scheduler only gives information related to memory usage.
