### ISSUE TITLE
Purpose of using a custom low-level allocator instead of `cudaMalloc`

### ISSUE THREAD

**Issue by Afront** [arcs-skku/EMDC_llvm#8]
In MMAP, a memory allocator was made using the Low-Level GPU Virtual Memory Management API.  Can I ask why a custom low-level allocator was created and used in `sync_main.cu` instead of using the standard `cudaMalloc` allocator?

**Comment by sungin-h** [comment]
We met the latency propagation among GPU pinned memory allocations. However, cudaMalloc is NVIDIA's private property. So we analyzed using Low-level GPU driver APIs. Those are private property too but they are separated into 4 steps.

For more information, please refer to https://developer.nvidia.com/blog/introducing-low-level-gpu-virtual-memory-management/

**Comment by Afront** [comment]
Okay, thank you!
