### ISSUE TITLE
Purporse of mismatch conditional in sycl_test

### ISSUE THREAD

**Issue by Afront** [arcs-skku/EMDC_llvm#9]
In `sycl_test`, there is a conditional that checks if there is a mismatch with the buffer. In which scenarios can there be a mismatch? How likely can these scenarios occur?

**Comment by sungin-h** [comment]
The buffer is uninitialized before launching the device kernel. After correct execution, the results are the same as each thread's Id.

So, if the kernel execution has failed, a mismatch occurs.
